app:
  name: web-server
env: production
web:
  prefork: false
  port: 3000
database:
  username:
  password:
  host:
  port:
  name:
  sslMode:
  timezone:
  pool:
    idle: 10
    max: 100
    lifetime: 300
